# Generated by Django 4.1.4 on 2023-01-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
